### ISSUE TITLE
Querying next page doesn't seem to work 

### ISSUE THREAD

**Issue by RJT1990** [paperswithcode/paperswithcode-client#3] opened 2020-10-31 15:29 UTC
>>> papers_page = client.paper_list(page=2, items_per_page=50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/pwc/lib/python3.7/site-packages/tea_client/handler.py", line 18, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/pwc/lib/python3.7/site-packages/paperswithcode_client-0.0.1-py3.7.egg/paperswithcode/client.py", line 98, in paper_list
  File "/opt/anaconda3/envs/pwc/lib/python3.7/site-packages/paperswithcode_client-0.0.1-py3.7.egg/paperswithcode/client.py", line 74, in __page
  File "/opt/anaconda3/envs/pwc/lib/python3.7/site-packages/paperswithcode_client-0.0.1-py3.7.egg/paperswithcode/client.py", line 65, in __parse
KeyError: 'page'
>>>

**Comment by ariecattan** [comment] 2020-12-20 09:36
I have the same issue, it happens only when `page=2` for all functions:
- `task_list()`
- `paper_list()`  
- `area_list()`
- `dataset_list()`

**Comment by alefnula** [comment] 2021-06-01 20:22
Tested this with the last version of the client and I cannot reproduce it with any call. I think this was a server issues that got fixed in the meantime.

**Closed by alefnula** 2021-06-01 20:22 UTC
